# Generated by Django 6.1.1 on 2026-09-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0017_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='anonimo',
            field=models.BooleanField(default=True, help_text='Se True, oculta o nome do autor publicamente.'),
        ),
    ]
