# Generated by Django 6.1.1 on 2026-10-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0018_producao_anonimo'),
        ('kipo_playground', '0018_producao_exibir_autor'),
    ]

    operations = [
    ]
