# Generated by Django 6.1.1 on 2026-10-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0019_merge_20261007_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producao',
            name='exibir_autor',
        ),
    ]
