# Generated by Django 4.1.4 on 2026-10-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kipo_playground', '0019_merge_20261007_1535'),
        ('kipo_playground', '0020_remove_producao_exibir_autor'),
    ]

    operations = [
    ]
